"""
PDF builder — renders the A4 CV HTML template to a single-page PDF via Playwright.

Public API
----------
render_html(cv_data)              -> str    (fully-injected HTML string)
build_pdf(cv_data, output_path)   -> bytes  (raw PDF; also writes file if path given)

Architectural contract
----------------------
Contact information (name, email, phone, linkedin, location) is NEVER
generated by the LLM.  This module injects those values from the hardcoded
_CONTACT dict below.  If a key is missing from _CONTACT it becomes an empty
string — it is never guessed, fabricated, or passed to the model.

cv_data shape (produced by TailorAgent — contact fields are absent by design):
{
  "title":      str,
  "summary":    str,
  "experience": [{"role", "company", "dates", "bullets": [str]}],
  "education":  [{"degree", "institution", "dates", "honors", "coursework"}],
  "military":   {"role", "unit", "dates"},          # optional
  "skills":     {"categories": [{"label", "items": [str]}]},
  "languages":  [{"language", "level"}],
  "volunteering": str,
}
"""
from __future__ import annotations

import html as _html
import re
from pathlib import Path

# ── Template resolution ───────────────────────────────────────────────────────
# Legacy default (kept for backward-compat — all existing callers pass no template_id)
TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "templates" / "cv_template.html"

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates" / "cv"

_TEMPLATE_MAP: dict[str, Path] = {
    "t1_classic":   _TEMPLATES_DIR / "t1_classic.html",
    "t2_modern":    _TEMPLATES_DIR / "t2_modern.html",
    "t3_executive": _TEMPLATES_DIR / "t3_executive.html",
}

TEMPLATE_REGISTRY: list[dict] = [
    {"id": "t1_classic",   "name": "Classic",   "description": "Traditional serif, black & white"},
    {"id": "t2_modern",    "name": "Modern",     "description": "Clean sans-serif, blue accent"},
    {"id": "t3_executive", "name": "Executive",  "description": "Bold headers, Georgia serif, charcoal"},
]


def _resolve_template(template_id: str | None) -> Path:
    """Return the Path for the requested template; falls back to the legacy default."""
    if template_id and template_id in _TEMPLATE_MAP:
        p = _TEMPLATE_MAP[template_id]
        if p.exists():
            return p
    return TEMPLATE_PATH

# ── Contact data — sourced exclusively from USER_PROFILE, never from the LLM ─
# user_profile.py is the single source of truth.  If a field is absent from
# USER_PROFILE["personal"], it becomes an empty string and the template
# placeholder is blanked.  Nothing is guessed or hardcoded here.
def _load_contact() -> dict:
    from backend.services.user_profile import USER_PROFILE
    p = USER_PROFILE.get("personal", {})
    return {
        "name":     p.get("name",     ""),
        "email":    p.get("email",    ""),
        "phone":    p.get("phone",    ""),
        "linkedin": p.get("linkedin", ""),
        "location": p.get("location", ""),
    }

# Contact field names — strip these from LLM output before injection
_CONTACT_KEYS = frozenset({"name", "email", "phone", "linkedin", "location"})


# ── Low-level helpers ─────────────────────────────────────────────────────────

def _e(text: str) -> str:
    """HTML-escape a plain-text string."""
    return _html.escape(str(text or ""), quote=False)


def _t(text: str, limit: int) -> str:
    """Escape and truncate to limit characters (for short display fields only).
    Never call this on experience bullets — use _e() directly there."""
    return _e(str(text or "")[:limit])


def _contact_line(value: str) -> str:
    """Return a full <span class="contact-line"> element, or empty string if blank.

    This ensures absent phone/location fields produce NO DOM node — not an
    empty span that wastes vertical space in the header.
    """
    stripped = str(value or "").strip()
    if not stripped:
        return ""
    return f'<span class="contact-line">{_e(stripped)}</span>'


def _inject(template: str, data: dict) -> str:
    """Replace every {{key}} placeholder; blank out any unreplaced ones."""
    for key, value in data.items():
        template = template.replace(f"{{{{{key}}}}}", str(value) if value is not None else "")
    return re.sub(r"\{\{[^}]+\}\}", "", template)


# ── Section HTML builders ─────────────────────────────────────────────────────

def _build_experience(entries: list[dict]) -> str:
    parts: list[str] = []
    for exp in entries[:5]:
        role    = _t(exp.get("role",    ""), 45)
        company = _t(exp.get("company", ""), 35)
        dates   = _t(exp.get("dates",   ""), 22)
        bullets_html = "".join(
            f"<li>{_e(str(b or ''))}</li>"
            for b in (exp.get("bullets") or [])[:6]
        )
        parts.append(
            f'<div class="exp-entry">'
            f'  <div class="entry-hdr">'
            f'    <div class="entry-meta">'
            f'      <span class="entry-role">{role}</span>'
            f'      <span class="entry-company">{company}</span>'
            f'    </div>'
            f'    <span class="entry-dates">{dates}</span>'
            f'  </div>'
            f'  <ul class="bullets">{bullets_html}</ul>'
            f'</div>'
        )
    return "\n".join(parts)


def _build_education(entries: list[dict]) -> str:
    parts: list[str] = []
    for edu in entries[:3]:
        degree      = _t(edu.get("degree",      ""), 60)
        institution = _t(edu.get("institution", ""), 35)
        dates       = _t(edu.get("dates",       ""), 20)
        honors      = _t(edu.get("honors",      ""), 60)
        coursework  = _t(edu.get("coursework",  ""), 80)

        honors_html     = f'<span class="edu-honors">{honors}</span>' if honors else ""
        coursework_html = (
            f'<span class="edu-coursework">Relevant: {coursework}</span>'
            if coursework else ""
        )

        parts.append(
            f'<div class="edu-entry">'
            f'  <div class="entry-hdr">'
            f'    <div class="entry-meta">'
            f'      <span class="edu-degree">{degree}</span>'
            f'      <span class="edu-institution">{institution}</span>'
            f'    </div>'
            f'    <span class="entry-dates">{dates}</span>'
            f'  </div>'
            f'  {honors_html}{coursework_html}'
            f'</div>'
        )
    return "\n".join(parts)


def _build_skills(skills_data: dict) -> str:
    """
    Render skills as plain inline text.  Delimiters are written directly into
    the HTML (not via CSS ::after) so they survive PDF rendering and never
    look like interactive web-UI badge components.
    """
    categories = (skills_data or {}).get("categories", [])
    if not categories:
        return ""
    cats_html = []
    for cat in categories[:4]:
        label = _t(cat.get("label", ""), 20)
        items = [_t(s, 25) for s in (cat.get("items") or [])[:6] if s]
        if not items:
            continue
        # Bullet-separated plain text — no background, no border, no badge look.
        items_text = " · ".join(items)
        cats_html.append(
            f'<div class="skill-cat">'
            f'  <span class="skill-cat-label">{label}</span>'
            f'  <span class="skill-items">{items_text}</span>'
            f'</div>'
        )
    if not cats_html:
        return ""
    return (
        f'<div class="side-sec">'
        f'  <span class="sec-title">Skills</span>'
        + "".join(cats_html) +
        f'</div>'
    )


def _build_languages(languages: list[dict]) -> str:
    if not languages:
        return ""
    rows = "".join(
        f'<div class="lang-row">'
        f'  <span class="lang-name">{_t(lang.get("language",""), 20)}</span>'
        f'  <span class="lang-level">{_t(lang.get("level",""), 35)}</span>'
        f'</div>'
        for lang in languages[:5]
    )
    return (
        f'<div class="side-sec">'
        f'  <span class="sec-title">Languages</span>'
        f'  {rows}'
        f'</div>'
    )


def _build_military(mil: dict | None) -> str:
    if not mil or not mil.get("role"):
        return ""
    role  = _t(mil.get("role",  ""), 45)
    unit  = _t(mil.get("unit",  ""), 60)   # raised from 40 — canonical unit string is 41 chars
    dates = _t(mil.get("dates", ""), 20)
    return (
        f'<div class="side-sec">'
        f'  <span class="sec-title">Military Service</span>'
        f'  <div class="entry-hdr">'
        f'    <div class="entry-meta">'
        f'      <span class="mil-role">{role}</span>'
        f'      <span class="mil-unit">{unit}</span>'
        f'    </div>'
        f'    <span class="entry-dates">{dates}</span>'
        f'  </div>'
        f'</div>'
    )


def _build_volunteering(text: str) -> str:
    if not text:
        return ""
    return (
        f'<div class="side-sec">'
        f'  <span class="sec-title">Volunteering</span>'
        f'  <div class="vol-text">{_t(text, 120)}</div>'
        f'</div>'
    )


# ── Public API ────────────────────────────────────────────────────────────────

def _flatten(cv_data: dict) -> dict:
    """Map TailorAgent JSON output to the flat placeholder dict the template needs.

    Contact fields come exclusively from _CONTACT.  Any contact-like keys in
    cv_data are silently dropped here so the LLM can never override them.
    """
    # Strip any contact fields the LLM may have accidentally included
    clean = {k: v for k, v in cv_data.items() if k not in _CONTACT_KEYS}

    flat: dict = {}

    # ── Contact — always from USER_PROFILE, never from LLM ──────────────────
    # name, email, linkedin → plain escaped strings (always rendered inside a
    #   static <span> in the template).
    # phone, location       → full <span> element or empty string; the template
    #   injects them raw so that a missing value leaves NO DOM node at all.
    contact = _load_contact()
    flat["name"]          = _e(contact.get("name",     ""))
    flat["email"]         = _e(contact.get("email",    ""))
    flat["linkedin"]      = _e(contact.get("linkedin", ""))
    flat["phone_line"]    = _contact_line(contact.get("phone",    ""))
    flat["location_line"] = _contact_line(contact.get("location", ""))

    # ── LLM-generated content ─────────────────────────────────────────────────
    flat["title"]   = _t(clean.get("title",   ""), 58)
    flat["summary"] = _t(clean.get("summary", ""), 400)

    flat["experience_blocks"]    = _build_experience(clean.get("experience", []))
    flat["education_blocks"]     = _build_education(clean.get("education",  []))
    flat["skills_section"]       = _build_skills(clean.get("skills", {}))
    flat["languages_section"]    = _build_languages(clean.get("languages", []))
    flat["military_section"]     = _build_military(clean.get("military"))
    flat["volunteering_section"] = _build_volunteering(clean.get("volunteering", ""))

    return flat


def render_html(cv_data: dict, template_id: str | None = None) -> str:
    """Return the fully-rendered HTML string for the CV."""
    template = _resolve_template(template_id).read_text(encoding="utf-8")
    return _inject(template, _flatten(cv_data))


async def build_pdf(cv_data: dict, output_path: str | Path | None = None,
                    template_id: str | None = None) -> bytes:
    """
    Render cv_data to a single-page A4 PDF using Playwright headless Chromium.

    Returns raw PDF bytes. If output_path is provided, also writes the file.
    """
    from playwright.async_api import async_playwright

    html_str = render_html(cv_data, template_id=template_id)

    async with async_playwright() as pw:
        browser = await pw.chromium.launch()
        page    = await browser.new_page()
        await page.set_content(html_str, wait_until="networkidle")
        pdf_bytes = await page.pdf(
            format="A4",
            print_background=True,
            prefer_css_page_size=True,
        )
        await browser.close()

    if output_path is not None:
        Path(output_path).write_bytes(pdf_bytes)

    return pdf_bytes
